FROM dpage/pgadmin4
# by default is the latest version

# docker pull dpage/pgadmin4
# download in terminal

ENV PGADMIN_DEFAULT_EMAIL=admin@admin.com
ENV PGADMIN_DEFAULT_PASSWORD=pass
# can add more ENV to customize 

EXPOSE 80

# docker build -t my_dba .
# docker run --name mydba  -p 8081:80 -d my_dba

# browser localhost:8081
# login admin@admin.com
# password pass
