version: '3.9'

services:
  db:
    image: postgres:12.12
    restart: always
    hostname: ${DB_HOST}
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - data:/var/lib/postgresql/data 
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - "${PG_PORT}:${PG_PORT}"
  dba:
    image: dpage/pgadmin4
    hostname: ${DBA_HOST}
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_NAME}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASS}
    ports:
      - "${PG_ADMIN_PORT}:80"
  api:
    build: ./api
    hostname: ${API_HOST}
    volumes: 
      - ./api/code:/app
    environment:
      - CONSUMER_PORT=${CONSUMER_PORT}
      - CONSUMER_ENDPOINT=${CONSUMER_ENDPOINT}
    command: python api.py
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
  consumer:
    build: ./consumer
    hostname: consumer
    volumes:
      - ./consumer/code:/app
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - API_ENDPOINT=${API_ENDPOINT}
    command: python consumer.py
    ports:
      - "${CONSUMER_PORT}:${CONSUMER_PORT}" 
  
volumes:
  data:
